### ISSUE TITLE
Select series to view

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#96] opened 2021-03-14 22:19 UTC
This happens regularly but not always. I can't see when it does and when it doesn't. I select a series, and either double click or go to Vieww Series/Image in the menu. Then it asks me to select a series. See screenshot

![image](https://user-images.githubusercontent.com/6051075/111086303-49905280-8513-11eb-99cd-16ed6856e307.png)

**Comment by JSousa-UoL** [comment] 2021-03-14 23:25
Duplicate of #97. 
I saw this issue after running merge script, but it's not because of merge only. 
This is a tricky one because there seem to be multiple causes.

**Comment by JSousa-UoL** [comment] 2021-03-21 20:25
I'm moving this to the first milestone. I found where the real cause is and I'm adding Steve to help solve this.
I spotted this while resolving issue #94.

What's happening is that if a Series has "Series" in its id/description then this will be removed when being read in TreeView and weaselXMLReader. This is because we have bits of code where we use the function replace "Study" and/or "Series" with "". This is similar to the Image display title we had a couple of weeks ago. Instead of replacing "Series" and then "-", we should be replacing "Series - " @IMI-TRISTAN

**Comment by IMI-TRISTAN** [comment] 2021-03-22 11:57
Made the above changes to replace functions to extract subject, study, series and image id from the labels in the tree view.

**Comment by JSousa-UoL** [comment] 2021-03-22 12:14
Thank you for doing this change, I will test this very shortly and close if I'm happy with it.

**Comment by JSousa-UoL** [comment] 2021-03-22 13:25
It's all good @IMI-TRISTAN , can I make a quick change to TreeView.py or are you using it?

**Comment by IMI-TRISTAN** [comment] 2021-03-22 13:39
Yes, I have finished with TreeView.py

**Comment by JSousa-UoL** [comment] 2021-03-22 14:02
Perfect, I just committed this change and it's all working well

**Closed by JSousa-UoL** 2021-03-22 14:02 UTC
