### ISSUE TITLE
Save XML at refresh only

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#61] opened 2021-02-21 21:38 UTC
Selected a large number of images to delete with Tutorial_delete.py - this takes a very long time. About 2 images per second.

**Comment by JSousa-UoL** [comment] 2021-02-22 10:29
Please hold this copy and delete tutorials, I didn't know you were advancing to these already. The generic DICOM tools for merge, copy and delete were created before the DeveloperModule, but only merge was included in the classes Image() and Series(). I still need to create a function called .copy(suffix="_Copy") and .delete(). Once these are done, you can call them directly from Scripting.py. For now, leave this to me and I'll let you know once I made progress.

**Comment by plaresmedima** [comment] 2021-02-22 10:47
OK I will pause. Deleting images should be approximately as fast as doing
it through windows explorer. I just made a test with a folder of 5000
images - it takes just a few seconds to delete all those in windows
explorer. It took me 25 minutes yesterday to delete 3000 images through
Weasel.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment] 2021-03-03 12:57
At some point this was ok, but now it's back to being slow. Will keep this open. May need @IMI-TRISTAN help on this.

**Comment by JSousa-UoL** [comment] 2021-03-09 09:25
I will need to create a delete and copy function for ImageList in Scripting.py.

**Comment by IMI-TRISTAN** [comment] 2021-03-09 09:56
This may have been caused by the recursive searching in the tree view being triggered after each delete. This is fixed now, so this problem may be fixed too

**Comment by JSousa-UoL** [comment] 2021-03-09 10:02
It did speed up a lot with your correction, but on my side I would like to try something that's needed for Steve's Scripting.py that will speed up even more. Eg. If you select 3000 images, it will remove and write the XML file 3000 times. I want to try to remove 3000 files and write the XML file only once.

**Comment by plaresmedima** [comment] 2021-03-09 12:11
Solution:

Read XML **once** when the DICOM folder is opened (or when a new XML is created)
Write XML to disk every time weasel is refreshed.

**Comment by IMI-TRISTAN** [comment] 2021-03-16 17:55
Removed xml file saves from insert and remove functions in weaselXMLReader.  Added an XML file save to the refresh treeview function.

**Closed by IMI-TRISTAN** 2021-03-16 17:55 UTC
