### ISSUE TITLE
closeSubWindow not closing the window

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#60] opened 2021-02-20 22:44 UTC
In Scripting line 79

displayImageCommon.closeSubWindow(self.objWeasel, self.path)

This does not close the subwindow. The Delete() is called in Tutorial_Delete.py

Apart from this issue, Tutorial_delete.py seems to be working.

**Comment by plaresmedima** [comment] 2021-03-04 22:17
Reopened as the problem still exists. If I delete an image that is on display, then the display is not closed, triggering an error if I then try to save the colour changes

Error in function saveDICOM_Image.updateSingleDicom: 'NoneType' object has no attribute 'PhotometricInterpretation'
Error in function saveDICOM_Image.saveDicomToFile: 'NoneType' object has no attribute 'group_dataset'

**Comment by JSousa-UoL** [comment] 2021-03-04 22:30
This was something mentioned by Charlotte in a UKRIN-MAPS meeting before. I'm adding @IMI-TRISTAN to this.
The problem is that if there is a display or window of an image, if that image is deleted, the window stays open. Should it automatically close?

**Comment by plaresmedima** [comment] 2021-03-04 23:36
I think everytime and image or series is deleted from the XML, there should be a check to see whether it is on display, and close the display (without saving) if it is.

**Comment by JSousa-UoL** [comment] 2021-03-05 12:07
Good suggestion, I'll have a think/look when I start working more intensively in the Delete button.

**Comment by IMI-TRISTAN** [comment] 2021-03-08 22:51
Since moving from displaying selected images to checked images, the Delete button on the image viewer screen had stopped working correctly.  I've now fixed it.  So this may have fixed the above issues.  DisplayImageCommon.closeSubWindow() is no longer used.

**Comment by JSousa-UoL** [comment] 2021-03-09 09:24
I didn't test Steve's changes because I made my commits only now, but this should be solved because I added a check in the delete function of the DeveloperTools where if the deleted image/series is on display, then it closes the window.

**Comment by JSousa-UoL** [comment] 2021-03-14 12:44
This is done and can be closed.

**Closed by JSousa-UoL** 2021-03-14 12:44 UTC
Labels: bug
